[project]
name = "tddbfhm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.20.0",
    "bcrypt>=4.2.0",
    "litestar[sqlalchemy,standard]==2.12.1",
    "pytest-asyncio>=0.24.0",
    "pytest>=8.3.3",
]
